# Generated by Django 4.1.3 on 2022-11-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_id', models.CharField(max_length=20, unique=True)),
                ('published_at', models.DateTimeField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('thumbnail_url', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='YoutubeVideos',
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['published_at'], name='api_video_publish_1748f9_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['yt_id'], name='api_video_yt_id_f4e18a_idx'),
        ),
    ]
